name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
      packages: read
      pages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
      - run: yarn --frozen-lockfile
      - id: date
        run: echo "date=$(TZ=America/Los_Angeles date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - id: cache-data
        uses: actions/cache@v4
        with:
          path: |
            docs/.observablehq/cache
          key: data-${{ hashFiles('docs/data/*') }}-${{ steps.date.outputs.date }}
      - if: steps.cache-data.outputs.cache-hit == 'true'
        run: find docs/.observablehq/cache -type f -exec touch {} +
      - run: yarn build
      - run: |
          mkdir -p dist/.well-known
          echo "${{ secrets.APPLE_DEVELOPER_MERCHANTID }}" > dist/.well-known/apple-developer-merchantid-domain-association
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - uses: actions/deploy-pages@v1
        if: github.ref == 'refs/heads/main'
